In [1]:
import torch

In [2]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.9394, 0.1616, 0.2814, 0.2813],
        [0.1351, 0.9844, 0.1524, 0.2958],
        [0.5543, 0.0728, 0.3174, 0.0365]])

Tensor B:
tensor([[0.1691, 0.5382, 0.7694, 0.8726],
        [0.7927, 0.2940, 0.2417, 0.3623],
        [0.3522, 0.1887, 0.0552, 0.9890]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])